services:
  - type: web
    name: earthquake-streamlit
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    repo: https://github.com/habibanezami/earthquake-dashboard
    branch: main
    rootDir: backend
