services:
  - type: web
    name: earthquake-streamlit
    env: python
    plan: free
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=10000
    repo: https://github.com/YOUR_USERNAME/earthquake-dashboard
    branch: main
    rootDir: backend
